import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

export const landingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9ff",
  },
  topBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    gap: 8,
  },
  topBannerText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
    textAlign: "center",
    flex: 1,
  },
  header: {
    backgroundColor: "#fff",
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1a4b8c",
  },
  loginButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 25,
    gap: 6,
    borderWidth: 2,
    borderColor: "#1a4b8c",
    shadowColor: "#1a4b8c",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  loginButtonText: {
    color: "#1a4b8c",
    fontWeight: "700",
    fontSize: 14,
  },
  heroSection: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 300,
  },
  heroIcon: {
    marginBottom: 16,
    textAlign: "center",
  },
  heroTitle: {
    fontSize: 36,
    fontWeight: "800",
    color: "#fff",
    textAlign: "center",
    marginBottom: 12,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  heroSubtitle: {
    fontSize: 18,
    color: "#fff",
    textAlign: "center",
    marginBottom: 8,
    opacity: 0.95,
  },
  heroDescription: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    opacity: 0.9,
    marginTop: 8,
  },
  section: {
    padding: 20,
    marginVertical: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1a4b8c",
    textAlign: "center",
  },
  sectionSubtitle: {
    fontSize: 15,
    color: "#6c757d",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 22,
  },
  carouselContainer: {
    marginTop: 20,
  },
  procedureSlide: {
    padding: 10,
  },
  procedureCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  procedureImagePlaceholder: {
    width: 200,
    height: 200,
    backgroundColor: "#e8f4f8",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  procedureTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1a4b8c",
    marginBottom: 12,
    textAlign: "center",
  },
  procedurePrice: {
    fontSize: 28,
    fontWeight: "800",
    color: "#00d4aa",
    marginVertical: 12,
  },
  procedureDescription: {
    fontSize: 14,
    color: "#6c757d",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  procedureButton: {
    backgroundColor: "#1a4b8c",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 25,
    marginTop: 10,
  },
  procedureButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  carouselIndicators: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    gap: 8,
  },
  indicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "rgba(26, 75, 140, 0.3)",
  },
  indicatorActive: {
    backgroundColor: "#00d4aa",
    width: 12,
    height: 12,
  },
  infoSection: {
    padding: 20,
    gap: 20,
  },
  infoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  infoTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1a4b8c",
    marginTop: 16,
    marginBottom: 12,
    textAlign: "center",
  },
  infoText: {
    fontSize: 14,
    color: "#6c757d",
    textAlign: "center",
    lineHeight: 22,
  },
  testimonialSection: {
    backgroundColor: "#e8f4f8",
    padding: 30,
    marginVertical: 20,
  },
  testimonialCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  testimonialText: {
    fontSize: 16,
    fontStyle: "italic",
    color: "#1a4b8c",
    textAlign: "center",
    lineHeight: 24,
    marginVertical: 16,
  },
  testimonialAuthor: {
    fontSize: 14,
    fontWeight: "700",
    color: "#00d4aa",
    marginTop: 8,
  },
  teamGrid: {
    gap: 20,
  },
  teamCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#e8f4f8",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 4,
    borderColor: "#00d4aa",
  },
  employeeName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a4b8c",
    marginBottom: 6,
    textAlign: "center",
  },
  employeeRole: {
    fontSize: 14,
    fontWeight: "600",
    color: "#00d4aa",
    marginBottom: 12,
  },
  employeeDesc: {
    fontSize: 13,
    color: "#6c757d",
    textAlign: "center",
    lineHeight: 20,
  },
  insuranceGrid: {
    gap: 16,
  },
  insuranceCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    borderTopWidth: 4,
    borderTopColor: "#00d4aa",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  insuranceName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a4b8c",
    marginVertical: 12,
  },
  insuranceDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginVertical: 4,
  },
  insuranceText: {
    fontSize: 13,
    color: "#6c757d",
  },
  footer: {
    padding: 40,
    alignItems: "center",
    marginTop: 40,
  },
  footerTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#fff",
    marginTop: 16,
    marginBottom: 8,
  },
  footerSubtitle: {
    fontSize: 16,
    color: "#fff",
    opacity: 0.9,
    marginBottom: 24,
  },
  socialLinks: {
    flexDirection: "row",
    gap: 20,
    marginVertical: 24,
  },
  socialButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  footerCopyright: {
    fontSize: 12,
    color: "#fff",
    opacity: 0.7,
    marginTop: 20,
    textAlign: "center",
  },
  floatingButton: {
    position: "absolute",
    bottom: '8%',
    right: 30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#25D366",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#25D366",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  headerButtonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    marginTop: 16,
    paddingHorizontal: 20,
  },



  headerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 5,
    paddingHorizontal: 16,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#1a4b8c",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  headerButtonText: {
    marginLeft: 8,
    color: "#1a4b8c",
    fontWeight: "600",
    fontSize: 7,
  },
})
